name: Build Extension
on: [push]
jobs:
  build_extension:
    name: Build the extension and save the artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get the requirements 
        run: |
          npm install
          npm install -g @vscode/vsce

      - name: Build Extension
        run: |
          vsce package

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: Built Extension
          path: /home/runner/work/Pwsh_In_Kotlin/Pwsh_In_Kotlin/powershell-in-kotlin-dsl-0.0.1.vsix
